<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NEWSPAPER
[
<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>
<!ENTITY NEWSPAPER "Newspaper: Integracija softverskih tehnologija,">
<!ENTITY PUBLISHER "Publisher: Andrija,">
<!ENTITY COPYRIGHT "Copyright: Viser">
]>

<NEWSPAPER>
<ARTICLE AUTHOR="Nemanja Cvijan" EDITOR="Andrija" DATE="3.25.2020" EDITION="1.0">
<HEADLINE>IST</HEADLINE>
<BYLINE>Vezba3</BYLINE>
<LEAD>Andrija</LEAD>
<BODY>Zadatak 5. Xml fajl sa ugradjenim DTD</BODY>
<NOTES>&NEWSPAPER;&PUBLISHER;&COPYRIGHT;</NOTES>
</ARTICLE>

</NEWSPAPER>